name: Jfrog Build & Scan

on:
  workflow_dispatch: # The repository will be scanned on demand
  push:
    branches:
      - main
      - develop
      - 'release/*'

# env:
# JFROG_CLI_AVOID_NEW_VERSION_WARNING: 'true'
  
permissions:
  actions: read           # for detecting the Github Actions environment
  id-token: write         # for creating OIDC tokens for signing
  contents: write         # for creating fixing pull requests and pushing changes
  pull-requests: write    # for creating pull requests to fix vulnerabilities
  security-events: write  # for uploading SARIF results to GitHub Code Scanning

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Install Maven 
        run: | 
          sudo apt-get update 
          sudo apt-get install -y maven
          
      # Add before the deploy step, right after setup-java
      - name: Check Maven Version
        run: mvn -version
        
      - name: Setup JFrog CLI 
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            version: '2.88.0'
            oidc-provider-name: setup-jfrog-cli
            oidc-audience: jfrog-github

      # OIDC Debugger
      - name: 'oidc-debugger-action'
        description: 'Print decoded OIDC token claims generated through Github Actions.'
        inputs:
          audience:
          description: 'The audience to use when requesting the JWT. Your Github server URL and repository owner (e.g. https://github.com/github).'
          required: true
          default: '${{ github.server_url }}/${{ github.repository }}'
      runs:
        using: "composite"
        steps:
          - name: Debug OIDC claims
            shell: bash
            env:
              AUDIENCE: "${{ inputs.audience }}"
            run: |
              TOKEN_JSON=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE")
              ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)
              echo "$ID_TOKEN" | awk -F. '{print $2}' | base64 -d 2>/dev/null | jq -r

      - name: Verify JFrog CLI & Artifactory auth
        run: |
          jf --version
          jf config show
          
      - name: Deploy with Maven
        id: deploy
        run: |
          jf rt ping || true
          jf mvn-config --repo-resolve-releases webgoat-libs-release --repo-resolve-snapshots webgoat-libs-snapshot --repo-deploy-releases webgoat-libs-release --repo-deploy-snapshots webgoat-libs-snapshot
          jf mvn -Dmaven.test.skip=true clean install
          jf rt build-collect-env
          jf rt build-add-git
          jf rt build-publish

      - name: JFrog Frogbot Repository Scan
        uses: jfrog/frogbot@v2
        id: frogbot
        with:
          oidc-provider-name: setup-jfrog-cli
          oidc-audience: jfrog-github
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_MIN_SEVERITY: "High"
          
